theme: jekyll-theme-cayman
title: Piaggi Research Group
description: MAterials and Molecules MOdeling and THeory (MAMMOTH) (sub)group within the Theory group at CIC nanoGUNE BRTA, San Sebastian, Spain
